name: arb_tooling
description: Dart tool to translate from ARB to CSV and viceversa.
version: 0.0.1
homepage: https://github.com/raulmabe/arb_tooling/
repository: https://github.com/raulmabe/arb_tooling/
issue_tracker: https://github.com/raulmabe/arb_tooling/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  csv: ^5.0.1
  mason_logger: ^0.1.0-dev.12
  meta: ^1.8.0
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

executables:
  arb_tooling:
